[package]
name = "mjai-reviewer"
version = "1.5.10"
authors = ["Equim"]
edition = "2021"
repository = "https://github.com/Equim-chan/mjai-reviewer"
license = "Apache-2.0"
description = "ğŸ”ğŸ€„ï¸ Review your Tenhou or Mahjong Soul (Jantama) log with mjai-compatible mahjong AIs."

[dependencies]
convlog = { path = "./convlog" }

anyhow = "1"
serde_json = "1"
tera = "1"
once_cell = "1"
chrono = "0.4"
ureq = "2"
opener = "0.6"
dunce = "1"
humantime-serde = "1"
url = "2"
serde_with = "3"
minify-html = "0.15"
fluent-templates = { version = "0.8.0", features = ["tera"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[workspace]
members = [
    ".",
    "convlog",
]

[profile.release]
debug = 1
lto = true
codegen-units = 1
